INSERT INTO  CitiesTable(CityID, CityName) VALUES(1, 'Jenin')
INSERT INTO  CitiesTable(CityID, CityName) VALUES(2, 'Tullkarm')
INSERT INTO  CitiesTable(CityID, CityName) VALUES(3, 'Nablus')
INSERT INTO  CitiesTable(CityID, CityName) VALUES(4, 'Rammallah')
INSERT INTO  CitiesTable(CityID, CityName) VALUES(5, 'Hebron')